import { allDistricts } from './site-data';

// Editorial selection, not a population ranking. Names checked against the local
// directory and municipal sources recorded in SEO_RELEASE_2026-10-01.md.
export const featuredNeighborhoods = [
  ['muratpasa', 'guzeloba', 'Güzeloba', 'Soğutma performansı', 'Klima çalıştığı hâlde oda serinlemiyorsa ayarlanan sıcaklığı, seçilen modu ve sorunun günün hangi saatinde arttığını not edin. Filtre, hava geçişi ve tesisat birlikte incelenmeden yalnızca gaz eklemek doğru bir çözüm olmayabilir.'],
  ['muratpasa', 'fener', 'Fener', 'İç üniteden su damlaması', 'Su damlamasının cihaz açılır açılmaz mı yoksa bir süre çalıştıktan sonra mı başladığını bildirin. Drenaj hattının eğimi, tıkanıklık ve yoğuşma koşulları kontrol edilir; duvarı ıslatan sorunun kaynağı belirlenmeden yalnızca hortum değişimi planlanmaz.'],
  ['muratpasa', 'caglayan', 'Çağlayan', 'Klima yer değişimi', 'Sökülüp yeniden kurulacak cihaz için eski ve yeni ünite konumlarını paylaşın. Boru güzergâhı, drenaj çıkışı ve dış üniteye erişim değerlendirilerek kullanılabilecek parçalar ile yenilenmesi gereken bağlantılar ayrılır.'],
  ['muratpasa', 'sirinyali', 'Şirinyalı', 'Ses ve titreşim incelemesi', 'Sesin iç üniteden mi dış üniteden mi geldiği ve fan hızına göre değişip değişmediği önemlidir. Sabitleme, fan ve titreşim aktarımı kontrol edilir; sesi dinlemek için cihazın kapağını açmanız gerekmez.'],
  ['muratpasa', 'meltem', 'Meltem', 'Birden fazla klima için bakım planı', 'Aynı adreste birden fazla cihaz varsa sayısını ve her birinin sorununu ayrı ayrı yazın. Çalışır durumdaki cihazların bakımı ile arızalı cihazın onarımı farklı işlerdir; işlem kapsamı ve ziyaret süresi buna göre görüşülür.'],
  ['muratpasa', 'meydankavagi', 'Meydankavağı', 'Koku ve bakım ihtiyacı', 'Kokunun ilk açılışta mı sürekli mi oluştuğunu, son bakımın ne zaman yapıldığını belirtin. Filtreyle birlikte iç ünite yüzeyleri ve su tahliyesi değerlendirilir; kokuyu bastıran ürünler temizlik ve neden tespitinin yerini tutmaz.'],
  ['muratpasa', 'yesilbahce', 'Yeşilbahçe', 'Dengesiz oda sıcaklığı', 'Hava akışının önündeki mobilya, açık kapılar ve kumandanın konumu konforu etkileyebilir. Talebinizde oda kullanımını ve cihazın üfleme yönünü anlatın; kapasite veya parça değişimi önerisi yerinde değerlendirmeden sonra yapılır.'],
  ['muratpasa', 'muratpasa', 'Muratpaşa', 'İşletmeye ulaşım ve servis talebi', 'Kaya Teknik’in işletme adresi Muratpaşa Mahallesi, 583 Sokak No: 3/A’dır. Yerinde klima incelemesi için aradığınızda bina ve cihaz bilgisini iletin; cihazı sökerek getirmeniz gerekip gerekmediğini önceden görüşün.'],
  ['muratpasa', 'konuksever', 'Konuksever', 'Aralıklı çalışma sorunu', 'Klimanın kaç dakika sonra durduğu, yeniden kendiliğinden başlayıp başlamadığı ve ekranda uyarı olup olmadığı incelemeyi kolaylaştırır. Elektrik beslemesi ile cihazın korumaya geçme nedenleri teknik kontrolde birbirinden ayrılır.'],
  ['muratpasa', 'kiziltoprak', 'Kızıltoprak', 'Zayıf hava üfleme', 'Fan hızı değiştiği hâlde hava akışı zayıf kalıyorsa filtre ve hava yolu kontrolü istenir. Talepte cihazın modunu belirtin; düşük üfleme tek başına soğutucu eksikliği veya kompresör arızası kanıtı değildir.'],
  ['muratpasa', 'memurevleri', 'Memurevleri', 'Sezon öncesi bakım hazırlığı', 'Uzun süre kapalı kalan klimayı kullanmaya başlamadan önce görünür kir ve su izlerini not edin. Bakımda erişilebilen filtreler, ünite temizliği ve drenaj değerlendirilir; performans şikâyeti varsa bakım talebine ayrıca ekleyin.'],
  ['muratpasa', 'ermenek', 'Ermenek', 'Yeni montaj öncesi keşif', 'Yeni cihazın montajında yalnızca duvar üzerindeki boşluk yeterli değildir. Dış ünitenin hava alması, bakım erişimi, boru mesafesi ve su tahliyesi birlikte planlanır; varsa mevcut tesisatın fotoğrafı ilk görüşmede yardımcı olur.'],
  ['kepez', 'varsak-karsiyaka', 'Varsak Karşıyaka', 'Varsak bölgesinde doğru adres', 'Varsak adı birden fazla mahalle için kullanılabildiğinden talebinizi Varsak Karşıyaka olarak belirtin. Site veya bina adı ve iç-dış ünite konumları randevu planını kolaylaştırır; kesin ziyaret saati görüşmede netleştirilir.'],
  ['kepez', 'varsak-esentepe', 'Varsak Esentepe', 'Isıtma modunda performans', 'Isıtma sırasında kısa süreli durma her zaman arıza anlamına gelmez. Duraklamanın süresini, ortam sıcaklığını ve varsa uyarıyı bildirin; normal çalışma davranışı ile teknik sorun model bilgisi üzerinden ayrılır.'],
  ['kepez', 'gunes', 'Güneş', 'Filtre ve ünite temizliği', 'Filtre temizliği ile kapsamlı klima bakımı aynı işlem değildir. Talepte yalnızca filtre mi yoksa iç ünite ve drenaj kontrolü de mi istediğinizi görüşün; cihazın yaşı ve son bakım tarihi iş kapsamının belirlenmesine yardımcı olur.'],
  ['kepez', 'sutculer', 'Sütçüler', 'Montaj sonrası kontrol', 'Yakın zamanda kurulan klimada ses, su akıtma veya yetersiz soğutma varsa montaj tarihini paylaşın. Bağlantılar, ünite seviyeleri ve tahliye yolu incelenir; sorun doğrudan cihaz arızası kabul edilmeden tesisat da değerlendirilir.'],
  ['kepez', 'kultur', 'Kültür', 'Kumanda ve çalışma modu', 'Kumandada seçili simgeyi ve cihazın verdiği tepkiyi bildirmek ilk değerlendirmeyi kolaylaştırır. Zamanlayıcı veya farklı mod ayarı ile teknik arıza birbirinden ayrılır; model bilgisi olmadan rastgele tuş kombinasyonları denenmemelidir.'],
  ['kepez', 'ahatli', 'Ahatlı', 'Dış üniteye erişim', 'Dış ünitenin balkon, cephe veya çatı konumunda olduğunu talepte belirtin. Güvenli erişim ve çalışma alanı ziyaret öncesinde görüşülür; ulaşılamayan bir ünitenin işlem süresi ile maliyeti standart bakım gibi değerlendirilemez.'],
  ['kepez', 'yeni-emek', 'Yeni Emek', 'Tekrarlayan su akıtma', 'Daha önce açılan drenaj hattı yeniden tıkanıyorsa eski müdahaleyi ve sorunun tekrarlama süresini paylaşın. Tahliye güzergâhı ve bağlantılar yeniden incelenerek yalnızca geçici su boşaltma yerine nedenin bulunması amaçlanır.'],
  ['kepez', 'duaci', 'Duacı', 'Uzun boru hattı olan cihazlar', 'İç ve dış ünitenin birbirinden uzak olduğu montajlarda yaklaşık mesafeyi ve kat farkını bildirin. Boru ölçüsü, izolasyon ve üreticinin modele özgü kurulum koşulları görülmeden standart gaz miktarı veya montaj bedeli söylenmez.'],
  ['kepez', 'demirel', 'Demirel', 'Ekranda arıza kodu', 'Kodun harf ve rakamlarını eksiksiz yazın; yanıp sönen lambalar varsa düzenini tarif edin. Aynı kod farklı model serilerinde farklı anlamlara gelebileceği için cihaz etiketi ile birlikte değerlendirme yapılır.'],
  ['kepez', 'yeni', 'Yeni', 'Bakım ve onarımın ayrılması', 'Yeni Mahalle için randevu alırken rutin temizlik isteğini ve varsa çalışmama şikâyetini ayrı ayrı belirtin. Bakım bir arızanın mutlaka giderileceği anlamına gelmez; gerekli onarım ve parça bedeli inceleme sonrası ayrıca açıklanır.'],
  ['konyaalti', 'hurma', 'Hurma', 'Düzenli bakım kapsamı', 'Bakım talebinde cihazın günlük çalışma süresi ve son temizliğinin tarihi yararlıdır. Filtre, iç ünite, dış ünite erişimi ve su tahliyesi birlikte görüşülür; birden fazla cihaz varsa her cihaz için işlem kapsamı netleştirilir.'],
  ['konyaalti', 'liman', 'Liman', 'Dış ünite ve bağlantılar', 'Dış ünitedeki görünür kirlenme veya bağlantı çevresindeki izleri güvenli mesafeden tarif edin. Teknik ekip erişim durumunu ve çalışma koşullarını değerlendirir; kapak açma ve elektrik bağlantılarına müdahale kullanıcıdan istenmez.'],
  ['konyaalti', 'uncali', 'Uncalı', 'Taşınma sırasında söküm', 'Taşınma tarihinde söküm ve yeni adreste montaj için ayrı zaman planı gerekebilir. Cihazın tekrar kullanılacağı adresi ve mevcut boru hattını bildirin; soğutucu devresine müdahale ve söküm teknik işlem olarak planlanır.'],
  ['konyaalti', 'altinkum', 'Altınkum', 'Hata kodu ile servis kaydı', 'Arıza kodunun fotoğrafı, model etiketi ve cihazın son normal çalıştığı zaman kayıt için yararlıdır. Yalnızca kod adına göre kart veya sensör sipariş edilmez; uyumluluk ve arıza nedeni önce kontrol edilir.'],
  ['konyaalti', 'gursu', 'Gürsu', 'Soğutma ve nem hissi', 'Klimanın çalışma modu ile odadaki hissedilen nemi birlikte belirtin. Fan ayarı ve kullanım koşulları incelenirken drenaj ve ünite performansı da değerlendirilir; daha düşük sıcaklık seçmek her sorunu çözmez.'],
  ['konyaalti', 'arapsuyu', 'Arapsuyu', 'İşyeri için ziyaret planı', 'İşyerinde klima işlemi isteniyorsa çalışma saatlerini ve cihazın kesintiye uygun olduğu zamanı paylaşın. Üniteye erişim, çevredeki eşyanın korunması ve birden fazla cihazın sırayla ele alınması görüşmede planlanır.'],
  ['konyaalti', 'sarisu', 'Sarısu', 'Yeni cihaz ve mevcut tesisat', 'Hazır tesisata cihaz bağlanacaksa boru çapı, hat uzunluğu ve tesisatın önceki kullanımı kontrol edilmelidir. Eski hattın her yeni modele uygun olduğu varsayılmaz; montaj öncesinde fotoğraf ve model bilgisiyle değerlendirme istenir.'],
  ['konyaalti', 'uluc', 'Uluç', 'Gece duyulan çalışma sesi', 'Düşük fan hızında veya belirli saatlerde fark edilen sesin sürekli mi aralıklı mı olduğunu not edin. İç ünite fanı, sabitleme ve dış üniteden yapıya geçen titreşim ayrı ayrı incelenerek gereksiz parça değişimi önlenmeye çalışılır.'],
  ['dosemealti', 'yesilbayir', 'Yeşilbayır', 'Açılmayan klima', 'Kumandanın ekranı ile iç ünitenin gösterge ışıklarının durumunu tarif edin. Besleme sorunu, kumanda iletişimi ve cihaz içi arıza teknik incelemede ayrılır; elektrik panosu veya cihaz kapağını açarak deneme yapmanız gerekmez.'],
  ['dosemealti', 'bahceyaka', 'Bahçeyaka', 'Bakım geçmişi bilinmeyen cihaz', 'Yeni taşındığınız adreste mevcut klimayı kullanacaksanız bakım geçmişinin bilinmediğini söyleyin. Görünür temizlik, tahliye ve çalışma durumu birlikte kontrol edilerek gerekli bakım ile olası onarım işlemleri ayrı değerlendirilir.'],
  ['dosemealti', 'altinkale', 'Altınkale', 'Çok odalı kullanımda planlama', 'Birden fazla odanın iklimlendirilmesi isteniyorsa oda sayısı, mevcut cihazlar ve kullanım saatleri paylaşılmalıdır. Tek cihazın tüm alanı aynı konforda tutacağı varsayılmaz; kapasite ve konum değerlendirmesi yerinde yapılır.'],
  ['dosemealti', 'yenikoy', 'Yeniköy', 'Isıtma ve soğutma geçişi', 'Mevsim geçişinde cihazın iki moddaki davranışını ayrı ayrı not edin. Isıtmada sorun yaşanırken soğutmanın çalışması veya tersi durum teknik değerlendirmeyi yönlendirir; kumanda ayarları ve model bilgisi talebe eklenir.'],
  ['dosemealti', 'ciplakli', 'Çıplaklı', 'Bina ve ünite erişimi', 'Site içindeki blok, kat ve dış ünitenin erişim biçimi servis ziyaretinin hazırlığını etkiler. Randevu öncesinde yönetimden gereken erişim koşullarını öğrenin; bina kurallarıyla uyumlu çalışma zamanı birlikte belirlenir.'],
  ['aksu', 'altintas', 'Altıntaş', 'Hazır tesisatın değerlendirilmesi', 'Klimaya ayrılan mevcut boru ve drenaj hattı varsa montajdan önce uçlarının ve dış ünite yerinin bilgisi paylaşılır. Kullanılmamış tesisatın da uygunluk kontrolü gerekir; hat temizliği ve bağlantı koşulları cihaz modeliyle birlikte ele alınır.'],
  ['aksu', 'pinarli', 'Pınarlı', 'Düşen soğutma verimi', 'Soğutmanın zaman içinde mi aniden mi azaldığını ve son yapılan işlemi belirtin. Hava akışı, genel çalışma ve kaçak ihtimali kontrol edilir; her performans kaybında otomatik olarak gaz dolumu yapılmaz.'],
  ['aksu', 'kundu', 'Kundu', 'Uzun süre çalışan cihazlar', 'Cihazın gün içinde ne kadar açık kaldığını ve kapatılabileceği zaman aralığını bildirin. Bakım planı kullanım süresine ve gözlenen belirtilere göre görüşülür; temizlik sırasında çalışma alanına erişim sağlanması gerekir.'],
  ['aksu', 'kemeragzi', 'Kemerağzı', 'Bir adreste farklı klima modelleri', 'Farklı marka veya model cihazlar için tek bir arıza açıklaması yerine her cihazın bilgisini ayrı iletin. Servis kapsamı ve parça uygunluğu model bazında değerlendirilir; toplam cihaz sayısı ziyaret planına eklenir.'],
  ['aksu', 'guzelyurt', 'Güzelyurt', 'Yer değişimi ve yeniden kurulum', 'Cihaz aynı binada başka odaya taşınacaksa yeni boru güzergâhı ile tahliye noktası önceden düşünülmelidir. Mevcut montaj parçalarının yeniden kullanımı kontrol sonucuna bağlıdır; söküm ve montaj kapsamı işlem öncesinde açıklanır.'],
].map(([district, slug, name, focus, advice]) => ({ district, slug, name, focus, advice }));

export function featuredNeighborhood(district?: string, slug?: string) {
  return featuredNeighborhoods.find(item => item.district === district && item.slug === slug);
}

export function neighborhoodSeo(district: string, slug: string) {
  const entry = featuredNeighborhood(district, slug);
  if (!entry) return undefined;
  const districtName = allDistricts.find(item => item.slug === district)!.name;
  return {
    title: `${entry.name} Klima Servisi | ${districtName} | Kaya Teknik`,
    description: `${districtName} ${entry.name} klima servisi: bakım, tamir ve montaj. ${entry.focus} için cihaz bilgilerinizi paylaşın; Kaya Teknik ile randevuyu görüşün.`,
  };
}
