export const guides = [
  {
    slug: 'klima-bakimi-ne-zaman-yapilmali',
    tr: { title: 'Klima bakımı ne zaman yapılmalı?', intro: 'Klima bakım zamanını kullanım yoğunluğu, ortam koşulları ve cihazın çalışma belirtileri belirler.', points: ['Filtrelerde gözle görülür kir birikmesi', 'Soğutma veya ısıtma performansında düşüş', 'Koku, olağandışı ses veya su damlatma görülmesi'] },
    en: { title: 'When should an air conditioner be maintained?', intro: 'Maintenance timing depends on use intensity, room conditions and the unit’s operating symptoms.', points: ['Visible dirt on filters', 'Reduced cooling or heating performance', 'Odour, unusual noise or water dripping'] },
    de: { title: 'Wann sollte eine Klimaanlage gewartet werden?', intro: 'Der Wartungszeitpunkt hängt von Nutzung, Raumbedingungen und dem Verhalten des Geräts ab.', points: ['Sichtbare Verschmutzung der Filter', 'Nachlassende Kühl- oder Heizleistung', 'Geruch, ungewöhnliche Geräusche oder Tropfwasser'] },
    ru: { title: 'Когда нужно обслуживать кондиционер?', intro: 'Срок обслуживания зависит от интенсивности использования, условий помещения и симптомов работы устройства.', points: ['Видимое загрязнение фильтров', 'Снижение эффективности охлаждения или обогрева', 'Запах, необычный шум или капли воды'] },
  },
  {
    slug: 'klima-sogutmuyor-ne-yapilmali',
    tr: { title: 'Klima soğutmuyorsa ne yapılmalı?', intro: 'Soğutmama sorunu tek bir nedene bağlı değildir. Kullanıcının güvenle yapabileceği basit kontrollerden sonra teknik inceleme gerekebilir.', points: ['Uzaktan kumanda modu ve sıcaklık ayarını kontrol edin', 'Filtrelerdeki yoğun kirlenmeyi gözden geçirin', 'Cihaz hata kodu veriyorsa modeliyle birlikte not alın'] },
    en: { title: 'What to do when an air conditioner does not cool?', intro: 'Poor cooling can have different causes. After simple safe checks, a technical inspection may be needed.', points: ['Check remote-control mode and temperature', 'Look for heavy filter contamination', 'Record any error code together with the model'] },
    de: { title: 'Was tun, wenn die Klimaanlage nicht kühlt?', intro: 'Schwache Kühlung kann verschiedene Ursachen haben. Nach einfachen sicheren Prüfungen kann eine technische Kontrolle nötig sein.', points: ['Modus und Temperatur der Fernbedienung prüfen', 'Filter auf starke Verschmutzung prüfen', 'Fehlercode zusammen mit dem Modell notieren'] },
    ru: { title: 'Что делать, если кондиционер не охлаждает?', intro: 'Недостаточное охлаждение может иметь разные причины. После простых безопасных проверок может понадобиться техническая диагностика.', points: ['Проверьте режим и температуру на пульте', 'Осмотрите фильтры на сильное загрязнение', 'Запишите код ошибки вместе с моделью'] },
  },
  {
    slug: 'klima-su-akitiyor-nedenleri',
    tr: { title: 'Klima su akıtıyor: olası nedenler', intro: 'İç üniteden su damlaması, yoğuşma tahliyesi veya bakım ihtiyacıyla ilgili olabilir. Elektrik aksamına su ulaşıyorsa cihazı kullanmayı bırakın.', points: ['Tahliye hattı tıkanmış olabilir', 'Filtre ve iç ünite temizliğe ihtiyaç duyabilir', 'Montaj eğimi veya yoğuşma hattı kontrol edilmelidir'] },
    en: { title: 'Air conditioner leaking water: possible causes', intro: 'Water dripping from an indoor unit may relate to condensate drainage or maintenance. Stop using the unit if water reaches electrical components.', points: ['The drain line may be blocked', 'Filters and indoor unit may need cleaning', 'Installation slope or condensate line may require inspection'] },
    de: { title: 'Klimaanlage tropft: mögliche Ursachen', intro: 'Wasser aus dem Innengerät kann mit Kondensatablauf oder Wartung zusammenhängen. Gerät nicht weiter nutzen, wenn Wasser elektrische Teile erreicht.', points: ['Die Ablaufleitung kann verstopft sein', 'Filter und Innengerät können gereinigt werden müssen', 'Montageneigung oder Kondensatleitung prüfen lassen'] },
    ru: { title: 'Кондиционер течёт: возможные причины', intro: 'Капли воды из внутреннего блока могут быть связаны со сливом конденсата или необходимостью обслуживания. Не используйте устройство, если вода попадает на электрику.', points: ['Дренажная линия может быть засорена', 'Фильтры и внутренний блок могут нуждаться в очистке', 'Нужна проверка уклона монтажа или дренажной линии'] },
  },
  {
    slug: 'klima-montajinda-dikkat-edilecekler',
    tr: { title: 'Klima montajında dikkat edilecekler', intro: 'Doğru montaj, cihazın verimi ve uzun süreli çalışması için önemlidir. Keşif sırasında iç ve dış ünite konumu birlikte değerlendirilmelidir.', points: ['İç ünitenin hava akışını engellemeyen konumu', 'Dış ünitenin güvenli ve erişilebilir yerleşimi', 'Boru, drenaj ve elektrik hattının uygun planlanması'] },
    en: { title: 'What to consider during air conditioner installation', intro: 'Correct installation matters for efficiency and long-term operation. Indoor and outdoor unit placement should be assessed together.', points: ['An indoor-unit location that does not obstruct airflow', 'Safe, accessible outdoor-unit placement', 'Proper planning of piping, drainage and electrical connection'] },
    de: { title: 'Worauf bei der Klimamontage zu achten ist', intro: 'Eine korrekte Montage ist für Effizienz und langfristigen Betrieb wichtig. Innen- und Außengerät sollten gemeinsam geplant werden.', points: ['Position des Innengeräts ohne blockierten Luftstrom', 'Sichere, zugängliche Position des Außengeräts', 'Passende Planung von Leitungen, Ablauf und Stromanschluss'] },
    ru: { title: 'На что обратить внимание при монтаже кондиционера', intro: 'Правильный монтаж важен для эффективности и долгой работы. Расположение внутреннего и наружного блоков следует оценивать вместе.', points: ['Место внутреннего блока без препятствий для воздушного потока', 'Безопасное и доступное размещение наружного блока', 'Грамотное планирование труб, дренажа и электроподключения'] },
  },
  {
    slug: 'klima-ariza-kodlari-nasil-kontrol-edilir',
    tr: { title: 'Klima arıza kodları nasıl kontrol edilir?', intro: 'Klima ekranındaki arıza kodları marka, seri ve modele göre değişir. Kodu doğru yorumlamak için cihazın model bilgisini ve kullanım kılavuzunu birlikte değerlendirmek gerekir.', points: ['Ekranda görünen kodu, yanıp sönen ışıkları ve cihazın modelini not alın', 'Kodu doğrulamak için yalnızca cihazın kendi kullanım kılavuzu veya teknik dokümanını kullanın', 'Elektrik kokusu, duman, sigorta atması veya suyun elektrik aksamına ulaşması durumunda cihazı kullanmayın', 'Arıza kodu ile birlikte soğutmama, ses, su akıtma veya koku gibi belirtileri servis talebinde paylaşın'] },
    en: { title: 'How to check air conditioner error codes', intro: 'Air-conditioner error codes vary by brand, series and model. Check the exact model and its manual before interpreting a code.', points: ['Note the displayed code, indicator lights and model number', 'Use only the unit’s manual or technical documentation to verify the code', 'Stop using the unit if there is burning smell, smoke, tripped breaker or water near electrical parts', 'Share the code together with symptoms such as poor cooling, noise, leaking or odour'] },
    de: { title: 'Wie prüft man Fehlercodes einer Klimaanlage?', intro: 'Fehlercodes unterscheiden sich je nach Marke, Baureihe und Modell. Prüfen Sie immer Modell und Handbuch zusammen.', points: ['Code, Kontrollleuchten und Modellnummer notieren', 'Code nur anhand der Geräteanleitung oder technischen Dokumentation prüfen', 'Bei Brandgeruch, Rauch, ausgelöstem Schutzschalter oder Wasser an elektrischen Teilen nicht weiter benutzen', 'Fehlercode zusammen mit Symptomen wie schwacher Kühlung, Geräuschen oder Tropfwasser mitteilen'] },
    ru: { title: 'Как проверить коды ошибок кондиционера', intro: 'Коды ошибок различаются в зависимости от марки, серии и модели. Их следует проверять только вместе с точной моделью и руководством.', points: ['Запишите код, индикаторы и номер модели', 'Проверяйте код только по руководству или технической документации устройства', 'Не используйте устройство при запахе гари, дыме, срабатывании автомата или попадании воды на электрику', 'Передайте код вместе с симптомами: слабое охлаждение, шум, течь или запах'] },
  },
] as const;
