export const locales = ['tr', 'en', 'de', 'ru'] as const;
export type Locale = (typeof locales)[number];
export function isLocale(value: string): value is Locale { return locales.some(locale => locale === value); }

const tr = {
  brand: 'KAYA TEKNİK', sub: 'Antalya Klima Servisi', service: 'Klima Servisi', home: 'Ana Sayfa', services: 'Hizmetler', areas: 'Hizmet Bölgeleri', brands: 'Markalar', guides: 'Klima Rehberi', contact: 'İletişim',
  hero: 'Antalya’da klima arıza, bakım ve montaj hizmeti', intro: 'Klima cihazınız için ihtiyaca uygun servis desteği. Öncelikli hizmet bölgelerimiz Muratpaşa, Konyaaltı, Kepez, Aksu ve Döşemealtı’dır.',
  priority: 'Öncelikli hizmet bölgeleri', moreAreas: 'Diğer Antalya ilçeleri', allAreas: 'Antalya klima hizmet bölgeleri', allBrands: 'Servis verilen klima markaları',
  independent: 'Kaya Teknik bağımsız teknik servis hizmeti sunar; üretici veya marka temsilciliği iddiasında bulunmaz.',
  request: 'Klima servis talebiniz mi var?', requestText: 'Cihaz marka/modeli, talep türü ve bulunduğunuz ilçeyi paylaşın; randevu uygunluğu hakkında size dönüş yapalım.',
  call: 'Hemen Ara', mobile: 'Mobil Ara', whatsapp: 'WhatsApp’tan Yaz', process: 'Hizmet süreci', scope: 'Hizmet kapsamı', related: 'İlgili klima hizmetleri',
  guideIntro: 'Klima bakımı, soğutma sorunları, su akıtma, montaj ve arıza kodları hakkında rehber yazılarımızı inceleyin.', guidePoints: 'Dikkat edilecek noktalar', errorGuide: 'Klima arıza kodu rehberini inceleyin', errorHeading: 'Arıza kodu ve model kontrolü',
  errorNote: 'Arıza kodları marka, seri ve modele göre değişir. Ekrandaki kodun tamamını, cihazın tam modelini ve görülen belirtiyi birlikte paylaşın. Açıklamayı cihazın kendi kullanım kılavuzundan doğrulayın.',
  areaIntro: 'Bu bölgedeki klima arıza, bakım, temizlik ve montaj talepleri cihazın durumu ve randevu uygunluğuna göre değerlendirilir.',
  evaluation: 'Cihaz değerlendirmesi', evaluationText: 'Çalışma modu, filtre durumu, hava akışı ve iç/dış ünitedeki belirtiler birlikte değerlendirilir. Sorunun ne zaman başladığını, bakım geçmişini ve cihazın bulunduğu alanı belirtin.',
  neighborhoodHeading: 'Mahallelerde klima servisi', neighborhoodIntro: 'Mahallenizi seçerek cihaz markanıza ve ihtiyacınıza uygun hizmet bilgilerine ulaşabilirsiniz.', brandIntro: 'Klima cihazınızın markasını ve modelini, gözlemlediğiniz belirtilerle birlikte paylaşın. Arıza, bakım, temizlik, montaj ve gaz dolumu için hizmet kapsamı değerlendirme sonrasında belirlenir.',
  availability: 'İşlem ve randevu uygunluğu; talep türü, cihazın teknik durumu, konumunuz ve ekip uygunluğu birlikte değerlendirilerek netleştirilir.',
  steps: ['Cihazın markasını, modelini ve varsa arıza kodunu paylaşın.', 'Arıza, bakım, montaj veya gaz dolumu ihtiyacını ve gözlemlediğiniz belirtileri belirtin.', 'İlçe, mahalle ve adres bilgisiyle randevu uygunluğunu teyit edin.'],
  faq: 'Sık sorulan sorular', faqItems: [['Servis talebinde hangi bilgiler gerekli?', 'Cihazın marka ve modeli, görülen belirti, talep edilen hizmet ve bulunduğunuz konum sürecin planlanmasına yardımcı olur.'], ['Hizmet uygunluğu nasıl belirlenir?', 'Talep türü, cihazın teknik durumu ve ekip uygunluğu birlikte değerlendirilir.']],
  partsHeading: 'Klima parça ve aksesuarları nelerdir?', partsText: 'Filtre, drenaj hortumu, boru izolasyonu, montaj aparatı, titreşim takozu, uzaktan kumanda ve bağlantı ekipmanları; bakım, montaj veya onarım sürecinde değerlendirilebilir.',
  retailHeading: 'Parça tedariki ve perakende satış', retailText: 'Klima parçaları ve aksesuarları için tedarik ve perakende satış imkânı vardır. Marka, model ve mümkünse parça görselini paylaşmanız uyumluluk ile güncel stok kontrolüne yardımcı olur.', partsNotice: 'Parça uygunluğu cihazın marka, model ve teknik durumuna göre belirlenir. Model doğrulanmadan orijinal veya muadil ürün iddiasında bulunulmaz.',
  partsFaq: [['Hangi klima parçaları bulunabilir?', 'Filtre, drenaj hortumu, boru izolasyonu, montaj aparatı, kumanda ve bağlantı ekipmanları için marka–model bilgisiyle uygunluk kontrolü yapılır.'], ['Parça tedariki ve perakende satış var mı?', 'Evet. Uygunluk ve güncel stok kontrolü sonrasında parça tedariki ile perakende satış imkânı değerlendirilir.']],
  serviceTitles: ['Klima Arıza ve Tamiri', 'Klima Bakım ve Temizlik', 'Klima Montaj ve Demontaj', 'Klima Gaz Dolumu', 'Klima Parçaları ve Aksesuarları'],
  serviceTexts: ['Soğutmama, su akıtma, ses, koku ve çalışma sorunları için arıza tespiti ve onarım.', 'Filtre, iç ünite ve dış ünite bakımıyla verimli ve hijyenik kullanım.', 'Yeni montaj, taşıma ve söküm işlemleri için keşif odaklı hizmet.', 'Kaçak kontrolü sonrasında cihazın ihtiyacına uygun soğutucu akışkan işlemi.', 'Filtre, drenaj hortumu, boru izolasyonu, montaj aparatı ve klima bağlantı ekipmanları hakkında bilgi.'],
  landingTitles: ['Klima Arıza Servisi', 'Klima Bakım Servisi', 'Klima Montaj Servisi', 'Klima Tamir Servisi'],
  quick: 'Hızlı erişim', search: 'Hızlı Arama', assistant: 'Bilgi Asistanı', assistantLabel: 'WhatsApp bilgi asistanı', close: 'Kapat', selectHeading: 'İlçe, mahalle ve marka seçin', selectIntro: 'Antalya’nın ilçeleri ve mahalleleri arasından seçim yapın.', district: 'İlçe', neighborhood: 'Mahalle', brandLabel: 'Klima markası', chooseDistrict: 'İlçe seçin', chooseNeighborhood: 'Mahalle seçin', chooseBrand: 'Marka seçin', openPage: 'Hizmet Sayfasını Aç', help: 'Size nasıl yardımcı olabiliriz?', helpText: 'Bir konu seçin; WhatsApp’ta hazır mesajla talebinizi iletin.', whatsappIntro: 'Merhaba, şu konuda bilgi almak istiyorum:', location: 'Konum', language: 'Dil',
};
export type Copy = typeof tr;
export const copy: Record<Locale, Copy> = {
  tr,
  en: {
    brand: 'KAYA TEKNİK', sub: 'Antalya Air Conditioner Service', service: 'Air Conditioner Service', home: 'Home', services: 'Services', areas: 'Service Areas', brands: 'Brands', guides: 'Air Conditioner Guide', contact: 'Contact',
    hero: 'Air conditioner repair, maintenance and installation in Antalya', intro: 'Air conditioner service tailored to your needs. Our priority service areas are Muratpaşa, Konyaaltı, Kepez, Aksu and Döşemealtı.', priority: 'Priority service areas', moreAreas: 'Other Antalya districts', allAreas: 'Air conditioner service areas in Antalya', allBrands: 'Air conditioner brands we service',
    independent: 'Kaya Teknik provides independent technical services and does not claim to represent any manufacturer or brand.', request: 'Need air conditioner service?', requestText: 'Share your unit’s brand and model, the service you need and your district. We will contact you about appointment availability.', call: 'Call Now', mobile: 'Call Mobile', whatsapp: 'Message on WhatsApp', process: 'Service process', scope: 'Service scope', related: 'Related air conditioner services',
    guideIntro: 'Read our guides on air conditioner maintenance, cooling problems, water leaks, installation and error codes.', guidePoints: 'Points to check', errorGuide: 'Read the air conditioner error code guide', errorHeading: 'Checking error codes and model details', errorNote: 'Error codes vary by brand, series and model. Share the complete code, exact model and symptoms together. Verify the explanation in the unit’s own manual.',
    areaIntro: 'Air conditioner repair, maintenance, cleaning and installation requests in this area are assessed according to the unit’s condition and appointment availability.', evaluation: 'Assessing your unit', evaluationText: 'Operating mode, filter condition, airflow and symptoms at the indoor and outdoor units are assessed together. Tell us when the problem started, the maintenance history and where the unit is installed.',
    neighborhoodHeading: 'Air conditioner service by neighbourhood', neighborhoodIntro: 'Choose your neighbourhood to find service information for your unit’s brand and your needs.', brandIntro: 'Share the brand and model of your air conditioner together with the symptoms you have observed. Repair, maintenance, cleaning, installation and refrigerant service requirements are determined after assessment.', availability: 'Service and appointment availability depend on the request, the unit’s technical condition, your location and team availability.',
    steps: ['Share the unit’s brand, model and any error code.', 'Describe whether you need repair, maintenance, installation or refrigerant service, along with the symptoms.', 'Confirm appointment availability with your district, neighbourhood and address.'],
    faq: 'Frequently asked questions', faqItems: [['What information is needed for a service request?', 'The unit’s brand and model, symptoms, requested service and location help us plan the next steps.'], ['How is service availability determined?', 'We assess the type of request, the unit’s condition and team availability together.']],
    partsHeading: 'Which parts and accessories are available?', partsText: 'Filters, drain hoses, pipe insulation, mounting brackets, vibration pads, remote controls and connection fittings may be needed for maintenance, installation or repair.', retailHeading: 'Parts supply and retail sales', retailText: 'We offer supply and retail sales of air conditioner parts and accessories. Share the brand, model and, if possible, a photo of the part so we can check compatibility and current stock.', partsNotice: 'Part compatibility depends on the unit’s brand, model and technical condition. No claim about an original or compatible replacement is made before the model is verified.',
    partsFaq: [['Which air conditioner parts can I enquire about?', 'We check filters, drain hoses, pipe insulation, brackets, remote controls and fittings against your unit’s brand and model.'], ['Do you supply parts and sell them directly?', 'Yes. Supply and retail options are assessed after compatibility and current stock have been checked.']],
    serviceTitles: ['Air Conditioner Repair', 'Air Conditioner Maintenance and Cleaning', 'Air Conditioner Installation and Removal', 'Air Conditioner Refrigerant Service', 'Air Conditioner Parts and Accessories'], serviceTexts: ['Diagnosis and repair for poor cooling, water leaks, noise, odours and operating problems.', 'Filter, indoor unit and outdoor unit maintenance for efficient, clean operation.', 'Site assessment for new installations, relocation and removal.', 'Refrigerant service suited to the unit’s needs after checking for leaks.', 'Information about filters, drain hoses, pipe insulation, mounting brackets and connection fittings.'], landingTitles: ['Air Conditioner Fault Diagnosis', 'Air Conditioner Maintenance', 'Air Conditioner Installation', 'Air Conditioner Repair'],
    quick: 'Quick access', search: 'Quick Search', assistant: 'Information Assistant', assistantLabel: 'WhatsApp information assistant', close: 'Close', selectHeading: 'Choose a district, neighbourhood and brand', selectIntro: 'Choose from Antalya’s districts and neighbourhoods.', district: 'District', neighborhood: 'Neighbourhood', brandLabel: 'Air conditioner brand', chooseDistrict: 'Choose a district', chooseNeighborhood: 'Choose a neighbourhood', chooseBrand: 'Choose a brand', openPage: 'Open Service Page', help: 'How can we help?', helpText: 'Choose a topic to prepare your enquiry in WhatsApp.', whatsappIntro: 'Hello, I would like information about:', location: 'Location', language: 'Language',
  },
  de: {
    brand: 'KAYA TEKNİK', sub: 'Klimaservice in Antalya', service: 'Klimaservice', home: 'Startseite', services: 'Leistungen', areas: 'Servicegebiete', brands: 'Marken', guides: 'Klimaanlagen-Ratgeber', contact: 'Kontakt', hero: 'Reparatur, Wartung und Montage von Klimaanlagen in Antalya', intro: 'Passender Service für Ihre Klimaanlage. Unsere vorrangigen Servicegebiete sind Muratpaşa, Konyaaltı, Kepez, Aksu und Döşemealtı.', priority: 'Vorrangige Servicegebiete', moreAreas: 'Weitere Bezirke von Antalya', allAreas: 'Klimaservicegebiete in Antalya', allBrands: 'Klimaanlagenmarken, die wir betreuen',
    independent: 'Kaya Teknik bietet unabhängige technische Dienstleistungen an und beansprucht keine Hersteller- oder Markenvertretung.', request: 'Benötigen Sie einen Klimaservice?', requestText: 'Teilen Sie uns Marke und Modell Ihres Geräts, die gewünschte Leistung und Ihren Bezirk mit. Wir melden uns zur Terminverfügbarkeit.', call: 'Jetzt anrufen', mobile: 'Mobil anrufen', whatsapp: 'WhatsApp-Nachricht', process: 'Serviceablauf', scope: 'Leistungsumfang', related: 'Weitere Leistungen für Klimaanlagen',
    guideIntro: 'Lesen Sie unsere Ratgeber zu Wartung, Kühlproblemen, Wasserlecks, Montage und Fehlercodes von Klimaanlagen.', guidePoints: 'Wichtige Prüfpunkte', errorGuide: 'Ratgeber zu Klimaanlagen-Fehlercodes lesen', errorHeading: 'Fehlercodes und Modellangaben prüfen', errorNote: 'Fehlercodes unterscheiden sich je nach Marke, Baureihe und Modell. Teilen Sie den vollständigen Code, die genaue Modellbezeichnung und die Symptome mit. Prüfen Sie die Bedeutung anhand der Geräteanleitung.',
    areaIntro: 'Anfragen zu Reparatur, Wartung, Reinigung und Montage in diesem Gebiet werden nach Gerätezustand und Terminverfügbarkeit geprüft.', evaluation: 'Beurteilung Ihres Geräts', evaluationText: 'Betriebsmodus, Filterzustand, Luftstrom und Symptome am Innen- und Außengerät werden gemeinsam betrachtet. Nennen Sie den Beginn des Problems, die bisherige Wartung und den Aufstellort.', neighborhoodHeading: 'Klimaservice nach Stadtviertel', neighborhoodIntro: 'Wählen Sie Ihr Stadtviertel, um passende Informationen zu Ihrer Gerätemarke und Ihrem Anliegen zu finden.', brandIntro: 'Teilen Sie Marke und Modell Ihrer Klimaanlage sowie die beobachteten Symptome mit. Der Bedarf an Reparatur, Wartung, Reinigung, Montage oder Kältemittel-Service wird nach einer Prüfung bestimmt.', availability: 'Leistung und Termin hängen von Ihrem Anliegen, dem technischen Gerätezustand, Ihrem Standort und der Verfügbarkeit des Teams ab.',
    steps: ['Teilen Sie Marke, Modell und gegebenenfalls den Fehlercode mit.', 'Beschreiben Sie den Bedarf an Reparatur, Wartung, Montage oder Kältemittel-Service sowie die Symptome.', 'Bestätigen Sie die Terminverfügbarkeit mit Bezirk, Stadtviertel und Adresse.'], faq: 'Häufig gestellte Fragen', faqItems: [['Welche Angaben werden für eine Serviceanfrage benötigt?', 'Marke, Modell, Symptome, gewünschte Leistung und Standort helfen bei der Planung.'], ['Wie wird die Serviceverfügbarkeit bestimmt?', 'Anliegen, Gerätezustand und Verfügbarkeit des Teams werden gemeinsam geprüft.']],
    partsHeading: 'Welche Teile und welches Zubehör gibt es?', partsText: 'Filter, Ablaufschläuche, Rohrisolierung, Montagehalterungen, Schwingungsdämpfer, Fernbedienungen und Anschlussmaterial können bei Wartung, Montage oder Reparatur benötigt werden.', retailHeading: 'Teilebeschaffung und Einzelverkauf', retailText: 'Wir bieten die Beschaffung und den Einzelverkauf von Klimaanlagenteilen und Zubehör an. Senden Sie Marke, Modell und möglichst ein Foto des Teils, damit Kompatibilität und aktueller Bestand geprüft werden können.', partsNotice: 'Die Eignung eines Teils hängt von Marke, Modell und technischem Zustand ab. Eine Aussage zu Original- oder Ersatzteilen erfolgt erst nach Prüfung des Modells.', partsFaq: [['Welche Klimaanlagenteile kann ich anfragen?', 'Filter, Ablaufschläuche, Rohrisolierung, Halterungen, Fernbedienungen und Anschlussmaterial werden anhand von Marke und Modell geprüft.'], ['Bieten Sie Teilebeschaffung und Einzelverkauf an?', 'Ja. Die Möglichkeiten werden nach Prüfung der Kompatibilität und des aktuellen Bestands geklärt.']],
    serviceTitles: ['Klimaanlagen-Reparatur', 'Wartung und Reinigung von Klimaanlagen', 'Montage und Demontage von Klimaanlagen', 'Kältemittel-Service für Klimaanlagen', 'Klimaanlagenteile und Zubehör'], serviceTexts: ['Fehlerdiagnose und Reparatur bei schwacher Kühlung, Wasserlecks, Geräuschen, Gerüchen und Betriebsstörungen.', 'Wartung von Filtern sowie Innen- und Außengeräten für einen effizienten, sauberen Betrieb.', 'Vor-Ort-Prüfung für Neuinstallation, Standortwechsel und Demontage.', 'Bedarfsgerechter Kältemittel-Service nach einer Dichtheitsprüfung.', 'Informationen zu Filtern, Ablaufschläuchen, Rohrisolierung, Halterungen und Anschlussmaterial.'], landingTitles: ['Fehlerdiagnose für Klimaanlagen', 'Klimaanlagenwartung', 'Klimaanlagenmontage', 'Klimaanlagenreparatur'],
    quick: 'Schnellzugriff', search: 'Schnellsuche', assistant: 'Info-Assistent', assistantLabel: 'WhatsApp-Info-Assistent', close: 'Schließen', selectHeading: 'Bezirk, Stadtviertel und Marke wählen', selectIntro: 'Wählen Sie einen Bezirk und ein Stadtviertel in Antalya.', district: 'Bezirk', neighborhood: 'Stadtviertel', brandLabel: 'Klimaanlagenmarke', chooseDistrict: 'Bezirk wählen', chooseNeighborhood: 'Stadtviertel wählen', chooseBrand: 'Marke wählen', openPage: 'Serviceseite öffnen', help: 'Wie können wir helfen?', helpText: 'Wählen Sie ein Thema, um Ihre Anfrage in WhatsApp vorzubereiten.', whatsappIntro: 'Guten Tag, ich möchte Informationen zu folgendem Thema:', location: 'Standort', language: 'Sprache',
  },
  ru: {
    brand: 'KAYA TEKNİK', sub: 'Сервис кондиционеров в Анталье', service: 'Сервис кондиционеров', home: 'Главная', services: 'Услуги', areas: 'Районы обслуживания', brands: 'Марки', guides: 'Руководства по кондиционерам', contact: 'Контакты', hero: 'Ремонт, обслуживание и монтаж кондиционеров в Анталье', intro: 'Сервис кондиционеров с учётом ваших потребностей. Приоритетные районы: Муратпаша, Коньяалты, Кепез, Аксу и Дёшемеалты.', priority: 'Приоритетные районы обслуживания', moreAreas: 'Другие районы Антальи', allAreas: 'Районы обслуживания кондиционеров в Анталье', allBrands: 'Обслуживаемые марки кондиционеров',
    independent: 'Kaya Teknik оказывает независимые технические услуги и не заявляет о представительстве производителя или бренда.', request: 'Нужен сервис кондиционера?', requestText: 'Укажите марку и модель устройства, нужную услугу и район. Мы свяжемся с вами по поводу доступного времени обслуживания.', call: 'Позвонить', mobile: 'Позвонить на мобильный', whatsapp: 'Написать в WhatsApp', process: 'Порядок обслуживания', scope: 'Состав услуг', related: 'Другие услуги для кондиционеров',
    guideIntro: 'Читайте наши материалы об обслуживании, проблемах с охлаждением, протечках, монтаже и кодах ошибок кондиционеров.', guidePoints: 'На что обратить внимание', errorGuide: 'Открыть руководство по кодам ошибок', errorHeading: 'Проверка кода ошибки и модели', errorNote: 'Коды ошибок различаются в зависимости от марки, серии и модели. Сообщите полный код, точную модель и симптомы. Уточняйте значение кода в руководстве именно к вашему устройству.',
    areaIntro: 'Заявки на ремонт, обслуживание, чистку и монтаж в этом районе рассматриваются с учётом состояния устройства и доступного времени обслуживания.', evaluation: 'Оценка состояния устройства', evaluationText: 'Режим работы, состояние фильтров, воздушный поток и симптомы у внутреннего и наружного блоков оцениваются вместе. Укажите, когда возникла проблема, историю обслуживания и место установки.', neighborhoodHeading: 'Обслуживание по микрорайонам', neighborhoodIntro: 'Выберите микрорайон, чтобы найти информацию об услугах для вашей марки кондиционера и вашей задачи.', brandIntro: 'Сообщите марку и модель кондиционера вместе с наблюдаемыми симптомами. Необходимость ремонта, обслуживания, чистки, монтажа или заправки хладагентом определяется после оценки.', availability: 'Возможность и время обслуживания зависят от заявки, технического состояния устройства, вашего адреса и доступности специалистов.',
    steps: ['Сообщите марку, модель и код ошибки, если он есть.', 'Укажите, нужен ли ремонт, обслуживание, монтаж или заправка хладагентом, и опишите симптомы.', 'Уточните время обслуживания, указав район, микрорайон и адрес.'], faq: 'Часто задаваемые вопросы', faqItems: [['Какие сведения нужны для заявки?', 'Марка и модель устройства, симптомы, нужная услуга и адрес помогают спланировать обслуживание.'], ['Как определяется возможность обслуживания?', 'Учитываются тип заявки, состояние устройства и доступность специалистов.']],
    partsHeading: 'Какие детали и аксессуары можно заказать?', partsText: 'При обслуживании, монтаже или ремонте могут потребоваться фильтры, дренажные шланги, изоляция труб, кронштейны, виброопоры, пульты и соединительные элементы.', retailHeading: 'Поставка деталей и розничная продажа', retailText: 'Доступны поставка и розничная продажа деталей и аксессуаров для кондиционеров. Сообщите марку, модель и по возможности приложите фото детали для проверки совместимости и наличия.', partsNotice: 'Совместимость детали зависит от марки, модели и технического состояния устройства. До проверки модели не делаются заявления об оригинальной детали или её аналоге.', partsFaq: [['О каких деталях можно узнать?', 'Совместимость фильтров, дренажных шлангов, изоляции труб, кронштейнов, пультов и соединительных элементов проверяется по марке и модели.'], ['Есть ли поставка деталей и розничная продажа?', 'Да. Возможности уточняются после проверки совместимости и текущего наличия.']],
    serviceTitles: ['Ремонт кондиционеров', 'Обслуживание и чистка кондиционеров', 'Монтаж и демонтаж кондиционеров', 'Заправка кондиционеров хладагентом', 'Детали и аксессуары для кондиционеров'], serviceTexts: ['Диагностика и ремонт при слабом охлаждении, протечках, шуме, запахах и сбоях в работе.', 'Обслуживание фильтров, внутреннего и наружного блоков для эффективной и чистой работы.', 'Оценка места установки перед новым монтажом, переносом или демонтажем.', 'Работы с хладагентом по потребностям устройства после проверки на утечки.', 'Информация о фильтрах, дренажных шлангах, изоляции труб, кронштейнах и соединительных элементах.'], landingTitles: ['Диагностика неисправностей кондиционеров', 'Обслуживание кондиционеров', 'Монтаж кондиционеров', 'Ремонт кондиционеров'],
    quick: 'Быстрый доступ', search: 'Быстрый поиск', assistant: 'Помощник', assistantLabel: 'Информационный помощник WhatsApp', close: 'Закрыть', selectHeading: 'Выберите район, микрорайон и марку', selectIntro: 'Выберите район и микрорайон Антальи.', district: 'Район', neighborhood: 'Микрорайон', brandLabel: 'Марка кондиционера', chooseDistrict: 'Выберите район', chooseNeighborhood: 'Выберите микрорайон', chooseBrand: 'Выберите марку', openPage: 'Открыть страницу услуг', help: 'Чем мы можем помочь?', helpText: 'Выберите тему, чтобы подготовить сообщение в WhatsApp.', whatsappIntro: 'Здравствуйте, хочу узнать о следующем:', location: 'Местоположение', language: 'Язык',
  },
};

export function areaTitle(locale: Locale, name: string) {
  return locale === 'tr' ? `${name} Klima Servisi` : `${copy[locale].service} — ${name}`;
}

// Confirmed by the owner on 2026-09-09. Appointment timing still requires confirmation.
const confirmedCoverage: Record<Locale, string> = {
 tr: 'Antalya’nın 19 ilçesinin tamamında klima arıza, bakım ve montaj hizmeti veriyoruz. Servis ziyaretinin zamanı, adresiniz ve yapılacak iş dikkate alınarak randevuyla belirlenir.',
 en: 'We provide air conditioner repair, maintenance and installation in all 19 districts of Antalya. Visits are arranged by appointment according to your address and the work required.',
 de: 'Wir bieten Reparatur, Wartung und Montage von Klimaanlagen in allen 19 Bezirken Antalyas an. Servicebesuche werden nach Adresse und Arbeitsumfang individuell vereinbart.',
 ru: 'Мы выполняем ремонт, обслуживание и монтаж кондиционеров во всех 19 районах Антальи. Время выезда согласовывается с учётом адреса и необходимых работ.'
};
for (const locale of locales) copy[locale].intro = confirmedCoverage[locale];
