import type { Locale } from './i18n';
import { information } from './site-content';

const kvkk: Record<Locale, string[]> = {
 tr: [
 'Bu metin, antalyaklimaservisi.tr üzerinden Kaya Teknik ile kurulan iletişim ve klima servis taleplerindeki kişisel veriler hakkında bilgi verir. İşletmeye aşağıdaki adres ve telefonlardan ulaşabilirsiniz.',
 'Telefon veya WhatsApp üzerinden ilettiğiniz ad, telefon, servis adresi, cihaz bilgileri ve arıza fotoğrafları; talebinizi değerlendirmek, randevu oluşturmak ve hizmeti yürütmek için kullanılır. Bu işlemler, KVKK madde 5/2(c) kapsamında sözleşmenin kurulması veya ifasıyla doğrudan ilgili gerekli işlemlere dayanır. Yasal kayıt yükümlülükleri için madde 5/2(ç), bir hakkın tesisi, kullanılması veya korunması için madde 5/2(e) uygulanabilir.',
 'Talebin yerine getirilmesi için gerekli bilgiler servis işlemini yürüten personele; kanuni yükümlülük varsa yetkili kamu kurumlarına iletilebilir. Siteye erişim sırasında barındırma sağlayıcısı Vercel teknik erişim kayıtlarını işleyebilir. WhatsApp kullanımı isteğe bağlıdır; bu hizmet kendi koşullarına tabidir ve yurt dışındaki altyapıları kullanabilir. Alternatif olarak telefonla iletişim kurabilirsiniz.',
 'Veriler, ilgili hizmet ve mevzuatın gerektirdiği süre boyunca saklanır; işleme nedeni ve zorunlu saklama süresi sona erdiğinde silinmesi, yok edilmesi veya anonimleştirilmesi gerekir. Gereksiz kimlik, sağlık veya ödeme kartı bilgilerini göndermeyin.',
 'KVKK madde 11 kapsamında verilerinizin işlenip işlenmediğini öğrenme, bilgi isteme, amacı ve amaca uygun kullanımı öğrenme, aktarılan kişileri öğrenme, düzeltme, koşulları oluştuğunda silme veya yok etme ve bu işlemlerin alıcılara bildirilmesini isteme haklarınız vardır. Otomatik analiz sonucu aleyhinize doğan sonuca itiraz edebilir ve kanuna aykırı işlem nedeniyle zararın giderilmesini talep edebilirsiniz. Başvurunuzu kimliğinizi doğrulamaya elverişli bilgilerle aşağıdaki işyeri adresine yazılı iletebilirsiniz.'
 ],
 en: [
 'This notice concerns personal data in communications and air-conditioning service requests made to Kaya Teknik through antalyaklimaservisi.tr. Contact details appear below.',
 'Your name, telephone number, service address, equipment details and fault photographs supplied by telephone or WhatsApp are used to assess requests, arrange appointments and provide service. Necessary processing directly related to entering into or performing a contract relies on Article 5/2(c) of Turkish Law No. 6698 (KVKK). Article 5/2(ç) may apply to legal record-keeping obligations and Article 5/2(e) to establishing, exercising or protecting rights.',
 'Information necessary for the service may be shared with the personnel carrying it out and, where legally required, competent public authorities. Hosting provider Vercel may process technical access logs. WhatsApp is optional, operates under its own terms and may use infrastructure outside Türkiye. You can contact us by telephone instead.',
 'Data is retained for the period required by the service and applicable legislation; once the processing purpose and mandatory retention period end, it must be deleted, destroyed or anonymised. Do not send unnecessary identification, health or payment-card information.',
 'Under KVKK Article 11 you may ask whether data is processed, request information about its purpose, use and recipients, seek correction or deletion/destruction when the conditions apply, and request that recipients be informed of these actions. You may object to an adverse result arising from automated analysis and seek compensation for unlawful processing. Send a written request to the business address below with information sufficient to verify your identity.'
 ],
 de: [
 'Diese Hinweise betreffen personenbezogene Daten bei Kontaktaufnahmen und Klimaservice-Anfragen an Kaya Teknik über antalyaklimaservisi.tr. Die Kontaktdaten stehen unten.',
 'Per Telefon oder WhatsApp mitgeteilte Namen, Telefonnummern, Einsatzadressen, Gerätedaten und Schadensfotos dienen der Bearbeitung Ihrer Anfrage, Terminplanung und Durchführung des Services. Erforderliche vertragsbezogene Verarbeitung stützt sich auf Artikel 5/2(c) des türkischen Gesetzes Nr. 6698 (KVKK). Für gesetzliche Aufbewahrungspflichten kann Artikel 5/2(ç), für die Begründung, Ausübung oder Verteidigung von Rechten Artikel 5/2(e) gelten.',
 'Erforderliche Angaben können an das ausführende Servicepersonal und bei gesetzlicher Verpflichtung an zuständige Behörden weitergegeben werden. Der Hostinganbieter Vercel kann technische Zugriffsprotokolle verarbeiten. WhatsApp ist freiwillig, unterliegt eigenen Bedingungen und kann Infrastruktur außerhalb der Türkei nutzen. Alternativ erreichen Sie uns telefonisch.',
 'Daten werden für die durch Service und Gesetz erforderliche Dauer aufbewahrt. Entfallen Zweck und verpflichtende Aufbewahrungsfrist, müssen sie gelöscht, vernichtet oder anonymisiert werden. Senden Sie keine unnötigen Ausweis-, Gesundheits- oder Zahlungskartendaten.',
 'Nach Artikel 11 KVKK können Sie Auskunft über Verarbeitung, Zweck, Verwendung und Empfänger sowie Berichtigung und bei Vorliegen der Voraussetzungen Löschung oder Vernichtung verlangen. Sie können die Benachrichtigung der Empfänger hierüber beantragen, nachteiligen Ergebnissen automatisierter Analysen widersprechen und Ersatz für Schäden durch rechtswidrige Verarbeitung verlangen. Schriftliche Anträge mit Angaben zur Identitätsprüfung richten Sie an die unten genannte Geschäftsadresse.'
 ],
 ru: [
 'Это уведомление касается персональных данных при обращении в Kaya Teknik и заказе обслуживания кондиционеров через antalyaklimaservisi.tr. Контактные данные указаны ниже.',
 'Имя, телефон, адрес обслуживания, сведения об оборудовании и фотографии неисправностей, переданные по телефону или WhatsApp, используются для рассмотрения заявки, согласования визита и выполнения работ. Необходимая обработка для заключения или исполнения договора основывается на статье 5/2(c) турецкого закона № 6698 (KVKK). Для выполнения обязанностей по хранению документов может применяться статья 5/2(ç), для установления, осуществления или защиты прав — статья 5/2(e).',
 'Необходимые сведения могут передаваться сотрудникам, выполняющим обслуживание, и уполномоченным государственным органам, если этого требует закон. Хостинг-провайдер Vercel может обрабатывать технические журналы доступа. WhatsApp используется добровольно, действует на собственных условиях и может использовать инфраструктуру за пределами Турции. Вы можете связаться с нами по телефону.',
 'Данные хранятся в течение срока, необходимого для обслуживания и предусмотренного законом. После прекращения цели обработки и обязательного срока хранения они должны быть удалены, уничтожены или обезличены. Не отправляйте ненужные сведения документов, медицинские данные или реквизиты платёжных карт.',
 'Статья 11 KVKK предоставляет право узнать об обработке данных, её целях, использовании и получателях, потребовать исправления и при наличии оснований удаления или уничтожения, а также уведомления получателей об этих действиях. Можно возражать против неблагоприятных результатов автоматического анализа и требовать возмещения вреда от незаконной обработки. Письменное обращение с данными для подтверждения личности можно направить по указанному ниже адресу.'
 ]
};
const terms: Record<Locale, string[]> = {
 tr: ['Bu koşullar antalyaklimaservisi.tr sitesinin kullanımına ilişkindir. Site, Kaya Teknik’in Antalya klima hizmetlerini tanıtmak ve iletişim sağlamak amacıyla sunulur.', 'Sitedeki bilgiler genel bilgilendirme amaçlıdır; cihazınıza özgü arıza tespiti veya kesin fiyat teklifi yerine geçmez. Randevu, servis bölgesi, yapılacak işlem, parça, toplam ücret ve varsa garanti koşulları işlem öncesinde ayrıca teyit edilir. Site üzerinden çevrim içi ödeme veya bağlayıcı sipariş alınmaz.', 'Marka ve logolar ilgili hak sahiplerine aittir. Kaya Teknik üreticilerden bağımsız özel teknik servistir; marka adının geçmesi yetkili servis ilişkisi oluşturmaz.', 'Siteyi hukuka aykırı, yanıltıcı veya güvenliğini bozacak şekilde kullanmayın. Elektrik ve soğutucu devresine müdahale gerektiren işlemleri uygun teknik personele bırakın. Harici hizmet bağlantıları ilgili sağlayıcının koşullarına tabidir.', 'Bu koşullar kanundan doğan tüketici haklarını ortadan kaldırmaz. Hizmete ilişkin sorularınızı veya taleplerinizi aşağıdaki iletişim kanallarından iletebilirsiniz.'],
 en: ['These terms govern use of antalyaklimaservisi.tr, which presents Kaya Teknik’s air-conditioning services in Antalya and provides contact channels.', 'Website information is general and does not replace diagnosis of your equipment or a firm quotation. Appointments, service coverage, work, parts, total charges and any warranty terms must be confirmed before work begins. The website does not accept online payments or binding orders.', 'Brands and logos belong to their respective rights holders. Kaya Teknik is a private service provider independent of manufacturers; a brand reference does not imply authorised-service status.', 'Do not use the site unlawfully, misleadingly or in ways that compromise security. Leave work on electrical and refrigerant circuits to appropriately qualified personnel. External services operate under their providers’ terms.', 'These terms do not remove statutory consumer rights. For service enquiries or requests, use the contact details below.'],
 de: ['Diese Bedingungen gelten für antalyaklimaservisi.tr. Die Website informiert über die Klimaservices von Kaya Teknik in Antalya und stellt Kontaktmöglichkeiten bereit.', 'Die Inhalte dienen der allgemeinen Information und ersetzen weder eine gerätespezifische Diagnose noch ein verbindliches Angebot. Termine, Einsatzgebiet, Arbeiten, Teile, Gesamtkosten und gegebenenfalls Garantiebedingungen werden vor Arbeitsbeginn gesondert bestätigt. Die Website nimmt keine Onlinezahlungen oder verbindlichen Bestellungen entgegen.', 'Marken und Logos gehören den jeweiligen Rechteinhabern. Kaya Teknik ist ein von Herstellern unabhängiger privater Dienstleister. Markennennungen begründen keinen Status als autorisierter Kundendienst.', 'Nutzen Sie die Website nicht rechtswidrig, irreführend oder sicherheitsgefährdend. Arbeiten an elektrischen Anlagen und Kältemittelkreisläufen gehören in die Hände geeigneter Fachkräfte. Für externe Dienste gelten die Bedingungen ihrer Anbieter.', 'Gesetzliche Verbraucherrechte bleiben unberührt. Fragen oder Anliegen zum Service können Sie über die unten angegebenen Kontaktdaten übermitteln.'],
 ru: ['Эти условия регулируют использование antalyaklimaservisi.tr. Сайт знакомит с услугами Kaya Teknik по обслуживанию кондиционеров в Анталье и предоставляет способы связи.', 'Информация носит общий характер и не заменяет диагностику вашего оборудования или окончательное ценовое предложение. Время визита, территория обслуживания, работы, запчасти, полная стоимость и возможная гарантия согласовываются до начала работ. Сайт не принимает онлайн-платежи или обязывающие заказы.', 'Марки и логотипы принадлежат соответствующим правообладателям. Kaya Teknik — частный сервис, независимый от производителей. Упоминание марки не означает статус авторизованного сервиса.', 'Не используйте сайт незаконным, вводящим в заблуждение или нарушающим безопасность способом. Работы с электрическими цепями и контуром хладагента поручайте соответствующим специалистам. Внешние сервисы действуют на условиях их поставщиков.', 'Эти условия не отменяют предусмотренные законом права потребителей. Вопросы и обращения по обслуживанию можно направить по указанным ниже контактам.']
};
export const legalTitles = {
 tr: ['KVKK Aydınlatma Metni', 'Gizlilik Politikası', 'Kullanım Koşulları'],
 en: ['Personal Data Protection Notice (KVKK)', 'Privacy Policy', 'Terms of Use'],
 de: ['Datenschutzhinweise (KVKK)', 'Datenschutzerklärung', 'Nutzungsbedingungen'],
 ru: ['Уведомление о защите персональных данных (KVKK)', 'Политика конфиденциальности', 'Условия использования']
};
export const legalPaths = ['kvkk', 'gizlilik-politikasi', 'kullanim-kosullari'];
export function legalParagraphs(locale: Locale, path: string): string[] {
 return path === 'kvkk' ? kvkk[locale] : path === 'kullanim-kosullari' ? [...terms[locale], information[locale].pricingText] : information[locale].privacyText;
}
