import type { Locale } from './i18n';

type Information = {
  about: string; privacy: string; skip: string; notFound: string; notFoundText: string;
  pricing: string; pricingText: string; contactTitle: string; contactText: string; review: string;
  aboutText: string[]; privacyText: string[]; serviceDetails: string[][];
};
export const information: Record<Locale, Information> = {
  tr: {
    about: 'Hakkımızda', privacy: 'Gizlilik ve iletişim bilgileri', skip: 'Ana içeriğe geç', notFound: 'Sayfa bulunamadı', notFoundText: 'Bu adres geçerli bir sayfaya ait değil. Ana sayfadan hizmet, bölge veya rehber seçebilirsiniz.',
    pricing: 'Ücret ve işlem onayı', pricingText: 'Ücret; cihazın modeli, arıza tespiti, parça ihtiyacı ve işin kapsamına göre değişebilir. Servis ziyaretinden önce tespit/ulaşım ücretini, işlem öncesinde toplam tutarı ve varsa parça garantisinin koşullarını teyit edin.',
    contactTitle: 'Servis talebi ve iletişim', contactText: 'Arıza belirtisini, marka–modeli, ilçe ve mahalleyi paylaşın. Randevu zamanı, hizmet kapsamı ve ücret bilgilerini telefon veya WhatsApp üzerinden netleştirin.', review: 'İçerik kontrol tarihi',
    aboutText: ['Kaya Teknik, Antalya’daki klima arıza, bakım, temizlik, montaj ve parça talepleri için bağımsız teknik servis bilgisi ve iletişim kanalları sunar.', 'Muratpaşa, Konyaaltı, Kepez, Aksu ve Döşemealtı öncelikli bölgelerdir. Diğer ilçelerdeki talepler için ekip ve randevu uygunluğu ayrıca teyit edilir.', 'Sitede geçen marka adları cihazı tanımlamak içindir. Üreticinin yetkili servisi veya resmi temsilcisi olduğumuz anlamına gelmez. İşlem kapsamını ve kullanılacak parçanın uygunluğunu talep sırasında doğrulayın.'],
    privacyText: ['Bu sitede üyelik veya çevrim içi ödeme formu bulunmaz. Telefon ve WhatsApp bağlantıları üzerinden iletişim kurabilirsiniz. Site kodunda reklam takip aracı kullanılmaz.', 'WhatsApp bağlantısını açmanız sizi üçüncü taraf bir hizmete götürür. Mesajınızı göndermeden önce içerik ve alıcıyı kontrol edin; WhatsApp’ın kendi gizlilik koşulları geçerlidir.', 'Servis talebinde paylaştığınız telefon, adres, cihaz ve arıza bilgileri talebin değerlendirilmesi ve iletişim kurulması için kullanılabilir. İhtiyaç olmayan kimlik veya ödeme bilgilerini mesajınıza eklemeyin.', 'Barındırma hizmeti, sitenin çalışması ve güvenliği için teknik erişim kayıtları tutabilir. Paylaştığınız bilgiler hakkında soru veya düzeltme talebi için 0242 344 05 07 numarasından iletişime geçebilirsiniz.'],
    serviceDetails: [
      ['Soğutmama veya ısıtmama, su damlatma, olağandışı ses ve çalışmama farklı nedenlerden kaynaklanabilir. Kontrol sırasında cihazın modeli, çalışma modu, filtreler, hava akışı ve varsa hata kodu birlikte değerlendirilir.', 'Yalnızca bir arıza koduna bakarak parça değişimine karar verilmez. Gözlenen belirtinin ne zaman başladığını, daha önce işlem yapılıp yapılmadığını ve cihazın bakım geçmişini paylaşın. Elektrik aksamını veya kapalı soğutucu devresini kendiniz açmayın.'],
      ['Bakım ihtiyacı kullanım yoğunluğu, ortam koşulları ve cihazın durumuna göre belirlenir. Filtre, iç ünite, dış ünite ve drenaj hattının durumu kontrol kapsamına girebilir; yapılacak işlemler cihazın kılavuzuna uygun olmalıdır.', 'Kullanıcının yapabileceği filtre temizliği için cihazın kılavuzunu izleyin ve önce enerjisini kesin. Filtreyi tamamen kurutmadan yerine takmayın. Basınçlı su veya kimyasalı elektrikli bölümlere uygulamayın; ayrıntılı temizlik için teknik destek alın.'],
      ['Montaj öncesinde iç ünitenin hava dağılımı, dış ünitenin güvenli yerleşimi ve erişilebilirliği değerlendirilir. Boru uzunluğu, drenaj eğimi ve elektrik hattının uygunluğu cihazın montaj talimatlarıyla birlikte kontrol edilir.', 'Söküm veya taşımada soğutucu akışkanın ve tesisatın uygun şekilde ele alınması gerekir. Yeni konum, mevcut tesisatın kullanılabilirliği ve gerekli ek malzemeler işleme başlamadan netleştirilmelidir. Montaj sonrasında çalışma ve drenaj kontrolü yapılması istenir.'],
      ['Soğutmanın zayıf olması tek başına gaz eksikliği anlamına gelmez. Kirli filtre, hava akışı, ayarlar veya başka arızalar benzer belirtiler verebilir. Gaz işlemi önerilmeden önce cihazın genel durumu ve olası kaçak değerlendirilmelidir.', 'Soğutucu akışkanın tipi ve miktarı cihazın etiketine ve üretici talimatına göre belirlenir. Kaçağın nedeni ele alınmadan yapılan tekrar dolumları kalıcı çözüm olmayabilir. Bu işlem uygun ekipman kullanan teknik personel tarafından yapılmalıdır.'],
      ['Parça talebinde cihazın tam modeli, seri etiketi ve istenen parçanın fotoğrafı uyumluluk kontrolünü kolaylaştırır. Görünüşü aynı olan parçaların elektriksel veya mekanik özellikleri farklı olabilir.', 'Stok, fiyat, teslim ve varsa parça garantisi koşullarını siparişten önce teyit edin. Montaj gerektiren parçalar için yalnızca parça bedeli ile işçilik bedelini ayrı ayrı netleştirin.'],
    ],
  },
  en: {
    about: 'About Us', privacy: 'Privacy and contact information', skip: 'Skip to main content', notFound: 'Page not found', notFoundText: 'This address does not match a page. Choose a service, area or guide from the home page.', pricing: 'Pricing and authorising work', pricingText: 'The price may depend on the model, diagnosis, parts and scope of work. Confirm any inspection or travel fee before the visit, and the total price and any parts warranty conditions before work begins.', contactTitle: 'Service enquiries and contact', contactText: 'Share the symptoms, brand and model, district and neighbourhood. Confirm the appointment, scope and price by phone or WhatsApp.', review: 'Content reviewed',
    aboutText: ['Kaya Teknik provides independent service information and contact channels for air conditioner repair, maintenance, cleaning, installation and parts enquiries in Antalya.', 'Muratpaşa, Konyaaltı, Kepez, Aksu and Döşemealtı are priority areas. Team and appointment availability for other districts must be confirmed separately.', 'Brand names on this site identify equipment. They do not imply that we are an authorised service centre or official representative. Confirm the scope of work and part compatibility when making your enquiry.'],
    privacyText: ['This site has no membership or online payment form. You can contact us using telephone and WhatsApp links. The site code does not include advertising trackers.', 'Opening a WhatsApp link takes you to a third-party service. Check the message and recipient before sending; WhatsApp’s own privacy terms apply.', 'Phone, address, equipment and fault details you share may be used to assess your request and contact you. Do not include unnecessary identity or payment information.', 'The hosting provider may retain technical access logs for operation and security. For questions or corrections concerning information you have shared, call +90 242 344 05 07.'],
    serviceDetails: [
      ['Poor cooling or heating, water dripping, unusual noise and failure to start can have different causes. Assessment considers the model, operating mode, filters, airflow and any error code together.', 'A fault code alone is not enough to decide on a replacement part. Explain when the symptom started, any earlier work and the maintenance history. Do not open electrical components or the sealed refrigerant circuit yourself.'],
      ['Maintenance needs depend on use, surroundings and the unit’s condition. Checks may cover the filters, indoor and outdoor units and drain line. Work should follow the equipment manual.', 'For user-serviceable filter cleaning, follow the manual and disconnect power first. Allow the filter to dry completely before refitting. Do not apply pressurised water or chemicals to electrical parts; seek technical help for deeper cleaning.'],
      ['Before installation, assess indoor airflow and a safe, accessible outdoor-unit position. Pipe length, drainage slope and electrical supply must be checked against the installation instructions.', 'Removal or relocation requires proper handling of refrigerant and pipework. Confirm the new location, suitability of existing connections and extra materials before work starts. Request operating and drainage checks after installation.'],
      ['Weak cooling does not by itself mean low refrigerant. Dirty filters, airflow, settings or other faults can cause similar symptoms. Assess the unit and possible leaks before recommending a refrigerant service.', 'Refrigerant type and quantity must follow the unit label and manufacturer instructions. Repeated refilling without addressing a leak may not solve the problem. This work requires technical personnel with suitable equipment.'],
      ['The exact model, identification label and a photo of the required part help with compatibility checks. Parts that look alike may have different electrical or mechanical specifications.', 'Confirm stock, price, delivery and any parts warranty before ordering. For parts requiring installation, clarify the parts price and labour charge separately.'],
    ],
  },
  de: {
    about: 'Über uns', privacy: 'Datenschutz und Kontaktinformationen', skip: 'Zum Hauptinhalt', notFound: 'Seite nicht gefunden', notFoundText: 'Unter dieser Adresse gibt es keine Seite. Wählen Sie auf der Startseite eine Leistung, ein Gebiet oder einen Ratgeber.', pricing: 'Kosten und Freigabe der Arbeiten', pricingText: 'Der Preis kann von Modell, Diagnose, Ersatzteilen und Arbeitsumfang abhängen. Klären Sie vor dem Besuch Prüf- und Anfahrtskosten sowie vor Arbeitsbeginn den Gesamtpreis und mögliche Teilegarantiebedingungen.', contactTitle: 'Serviceanfrage und Kontakt', contactText: 'Nennen Sie Symptome, Marke, Modell, Bezirk und Stadtviertel. Klären Sie Termin, Leistungsumfang und Preis telefonisch oder per WhatsApp.', review: 'Inhalt geprüft',
    aboutText: ['Kaya Teknik bietet unabhängige Serviceinformationen und Kontaktmöglichkeiten für Reparatur, Wartung, Reinigung, Montage und Teileanfragen für Klimaanlagen in Antalya.', 'Muratpaşa, Konyaaltı, Kepez, Aksu und Döşemealtı sind vorrangige Gebiete. Für weitere Bezirke müssen Team- und Terminverfügbarkeit gesondert bestätigt werden.', 'Die Markennamen auf dieser Website dienen der Gerätezuordnung. Sie bedeuten keine autorisierte Servicepartnerschaft oder offizielle Vertretung. Klären Sie den Arbeitsumfang und die Eignung von Ersatzteilen bei Ihrer Anfrage.'],
    privacyText: ['Diese Website enthält weder ein Mitgliedskonto noch ein Online-Zahlungsformular. Kontakt ist über Telefon- und WhatsApp-Links möglich. Der Website-Code enthält keine Werbetracker.', 'Ein WhatsApp-Link führt zu einem Drittanbieter. Prüfen Sie Nachricht und Empfänger vor dem Versand; es gelten die Datenschutzbedingungen von WhatsApp.', 'Mitgeteilte Telefonnummern, Adressen sowie Geräte- und Fehlerangaben können zur Bearbeitung Ihrer Anfrage und zur Kontaktaufnahme genutzt werden. Senden Sie keine unnötigen Identitäts- oder Zahlungsdaten.', 'Der Hostinganbieter kann technische Zugriffsprotokolle für Betrieb und Sicherheit führen. Bei Fragen oder Korrekturwünschen zu Ihren Angaben erreichen Sie uns unter +90 242 344 05 07.'],
    serviceDetails: [
      ['Schwache Kühl- oder Heizleistung, Tropfwasser, ungewöhnliche Geräusche und Startprobleme können verschiedene Ursachen haben. Modell, Betriebsmodus, Filter, Luftstrom und Fehlercode werden gemeinsam betrachtet.', 'Ein Fehlercode allein reicht nicht für die Entscheidung über einen Teiletausch. Nennen Sie Beginn der Symptome, frühere Arbeiten und Wartungshistorie. Öffnen Sie elektrische Bauteile oder den geschlossenen Kältemittelkreislauf nicht selbst.'],
      ['Der Wartungsbedarf hängt von Nutzung, Umgebung und Gerätezustand ab. Filter, Innen- und Außengerät sowie die Ablaufleitung können zur Prüfung gehören. Arbeiten müssen nach Geräteanleitung erfolgen.', 'Befolgen Sie bei der für Nutzer vorgesehenen Filterreinigung die Anleitung und trennen Sie zuerst die Stromversorgung. Setzen Sie den Filter erst vollständig trocken ein. Kein Druckwasser oder Reinigungsmittel auf elektrische Teile sprühen; für eine gründliche Reinigung technische Hilfe anfordern.'],
      ['Vor der Montage werden Luftverteilung im Raum sowie ein sicherer, zugänglicher Standort des Außengeräts geprüft. Rohrlänge, Ablaufgefälle und Stromanschluss müssen zur Montageanleitung passen.', 'Demontage und Standortwechsel erfordern einen sachgerechten Umgang mit Kältemittel und Leitungen. Klären Sie neuen Standort, Nutzbarkeit vorhandener Anschlüsse und Zusatzmaterial vor Arbeitsbeginn. Nach der Montage sollten Betrieb und Kondensatablauf geprüft werden.'],
      ['Schwache Kühlung bedeutet nicht automatisch Kältemittelmangel. Verschmutzte Filter, Luftstrom, Einstellungen oder andere Fehler können ähnliche Symptome auslösen. Vor einem Kältemittel-Service sollten Gerät und mögliche Lecks geprüft werden.', 'Kältemittelart und Füllmenge richten sich nach Typenschild und Herstellerangaben. Wiederholtes Nachfüllen ohne Behebung einer Undichtigkeit ist möglicherweise keine dauerhafte Lösung. Diese Arbeiten erfordern Fachpersonal und geeignete Ausrüstung.'],
      ['Genaue Modellbezeichnung, Typenschild und ein Foto des gewünschten Teils erleichtern die Kompatibilitätsprüfung. Ähnlich aussehende Teile können andere elektrische oder mechanische Eigenschaften haben.', 'Klären Sie Bestand, Preis, Lieferung und mögliche Teilegarantie vor der Bestellung. Bei einzubauenden Teilen sollten Materialpreis und Arbeitskosten getrennt bestätigt werden.'],
    ],
  },
  ru: {
    about: 'О нас', privacy: 'Конфиденциальность и контактная информация', skip: 'Перейти к основному содержимому', notFound: 'Страница не найдена', notFoundText: 'По этому адресу нет страницы. Выберите услугу, район или руководство на главной странице.', pricing: 'Стоимость и согласование работ', pricingText: 'Цена может зависеть от модели, диагностики, деталей и объёма работ. До визита уточните плату за диагностику и выезд, а до начала работ — общую сумму и условия возможной гарантии на детали.', contactTitle: 'Заявка на обслуживание и контакты', contactText: 'Укажите симптомы, марку, модель, район и микрорайон. Уточните время, объём работ и стоимость по телефону или в WhatsApp.', review: 'Дата проверки материала',
    aboutText: ['Kaya Teknik предоставляет информацию о независимом обслуживании и контакты для заявок на ремонт, чистку, обслуживание, монтаж и детали кондиционеров в Анталье.', 'Приоритетные районы — Muratpaşa, Konyaaltı, Kepez, Aksu и Döşemealtı. Для остальных районов доступность специалистов и времени обслуживания подтверждается отдельно.', 'Названия марок на сайте служат для обозначения оборудования. Они не означают, что мы являемся авторизованным сервисом или официальным представителем. При обращении уточняйте объём работ и совместимость деталей.'],
    privacyText: ['На сайте нет формы регистрации или онлайн-оплаты. Связаться с нами можно по телефону и через WhatsApp. В код сайта не встроены рекламные трекеры.', 'Ссылка WhatsApp ведёт в сторонний сервис. Перед отправкой проверьте текст и получателя; действуют собственные правила конфиденциальности WhatsApp.', 'Переданные телефон, адрес, сведения об устройстве и неисправности могут использоваться для рассмотрения заявки и связи с вами. Не отправляйте ненужные сведения о документах или платёжные данные.', 'Поставщик хостинга может вести технические журналы доступа для работы и безопасности сайта. По вопросам или для исправления переданных сведений звоните +90 242 344 05 07.'],
    serviceDetails: [
      ['Слабое охлаждение или обогрев, протечки, необычный шум и отказ запуска могут иметь разные причины. Модель, режим, фильтры, воздушный поток и код ошибки оцениваются вместе.', 'Одного кода ошибки недостаточно для решения о замене детали. Сообщите, когда возникли симптомы, какие работы выполнялись ранее и как обслуживалось устройство. Не вскрывайте самостоятельно электрические узлы или закрытый контур хладагента.'],
      ['Потребность в обслуживании зависит от использования, окружающих условий и состояния устройства. Проверка может включать фильтры, внутренний и наружный блоки и дренаж. Работы должны соответствовать руководству устройства.', 'При разрешённой пользователю чистке фильтра следуйте инструкции и сначала отключите питание. Устанавливайте фильтр только после полного высыхания. Не направляйте воду под давлением или химические средства на электрические части; для глубокой чистки обратитесь к специалисту.'],
      ['Перед монтажом оценивают распределение воздуха в помещении и безопасное, доступное место наружного блока. Длину труб, уклон дренажа и электропитание проверяют по инструкции монтажа.', 'Демонтаж и перенос требуют правильного обращения с хладагентом и трубами. До начала работ согласуйте новое место, пригодность существующих соединений и дополнительные материалы. После монтажа необходима проверка работы и отвода конденсата.'],
      ['Слабое охлаждение само по себе не доказывает нехватку хладагента. Грязные фильтры, воздушный поток, настройки и другие неисправности могут давать похожие симптомы. Перед заправкой следует оценить устройство и возможные утечки.', 'Тип и количество хладагента определяются по табличке устройства и инструкции производителя. Повторная заправка без устранения утечки может не решить проблему. Работы выполняются техническими специалистами с подходящим оборудованием.'],
      ['Точная модель, табличка устройства и фото нужной детали помогают проверить совместимость. Внешне одинаковые детали могут отличаться электрическими или механическими характеристиками.', 'До заказа уточните наличие, цену, доставку и возможную гарантию на детали. Если требуется установка, отдельно согласуйте стоимость детали и работы.'],
    ],
  },
};

// Owner confirmed a 1-year parts replacement warranty; publish no fixed service fee or distance rule.
const confirmedBusinessCopy: Record<Locale, { coverage: string; pricing: string }> = {
 tr: { coverage: 'Antalya’nın 19 ilçesinin tamamına servis veriyoruz. Muratpaşa, Konyaaltı, Kepez, Aksu ve Döşemealtı öncelikli bölgelerimizdir; tüm ilçelerde ziyaret günü ve saati randevu sırasında netleştirilir.', pricing: 'Güncel hizmet bedeli için iletişime geçiniz. Parça değişiminde 1 yıl garanti verilmektedir. Garanti kapsamı ve koşulları hakkında işlem öncesinde bilgi alabilirsiniz.' },
 en: { coverage: 'We serve all 19 districts of Antalya. Muratpaşa, Konyaaltı, Kepez, Aksu and Döşemealtı are priority areas; visit dates and times are confirmed when booking in every district.', pricing: 'Please contact us for current service charges. Parts replacement comes with a 1-year warranty. Please ask about warranty coverage and conditions before the work begins.' },
 de: { coverage: 'Wir bedienen alle 19 Bezirke Antalyas. Muratpaşa, Konyaaltı, Kepez, Aksu und Döşemealtı sind vorrangige Gebiete; Besuchstag und Uhrzeit werden in allen Bezirken bei der Terminvereinbarung bestätigt.', pricing: 'Bitte kontaktieren Sie uns für die aktuellen Servicekosten. Auf den Austausch von Teilen gewähren wir 1 Jahr Garantie. Informationen zu Umfang und Bedingungen der Garantie erhalten Sie vor Beginn der Arbeiten.' },
 ru: { coverage: 'Мы обслуживаем все 19 районов Антальи. Муратпаша, Коньяалты, Кепез, Аксу и Дёшемеалты — приоритетные районы; дата и время выезда во всех районах подтверждаются при записи.', pricing: 'Свяжитесь с нами, чтобы уточнить актуальную стоимость услуг. На замену деталей предоставляется гарантия 1 год. Условия и объём гарантии можно уточнить до начала работ.' }
};
for (const locale of ['tr', 'en', 'de', 'ru'] as const) {
 information[locale].aboutText[1] = confirmedBusinessCopy[locale].coverage;
 information[locale].pricingText = confirmedBusinessCopy[locale].pricing;
}

// Public pricing headings, confirmed wording.
information.tr.pricing = "Güncel hizmet bedeli ve garanti";
information.en.pricing = "Current service charges and warranty";
information.de.pricing = "Aktuelle Servicekosten und Garantie";
information.ru.pricing = "Актуальная стоимость услуг и гарантия";

// Mobile service team confirmed by the owner.
information.tr.aboutText.push('Mobil servis araçlarımız, profesyonel ustalarımız ve çıraklarımızla Antalya’nın 19 ilçesinde hizmet veriyoruz.');
information.en.aboutText.push('With our mobile service vehicles, professional technicians and apprentices, we serve all 19 districts of Antalya.');
information.de.aboutText.push('Mit unseren mobilen Servicefahrzeugen, professionellen Fachkräften und Auszubildenden sind wir in allen 19 Bezirken Antalyas für Sie im Einsatz.');
information.ru.aboutText.push('Наши профессиональные мастера и ученики выезжают на сервисных автомобилях для обслуживания всех 19 районов Антальи.');
